# Generated by Django 2.0.1 on 2018-02-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='Имя')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=48, null=True, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, default=None, max_length=128, null=True, verbose_name='Email')),
                ('description', models.TextField(blank=True, default=None, null=True, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Subscriber',
                'verbose_name_plural': 'Subscribers',
            },
        ),
        migrations.AlterModelOptions(
            name='section2',
            options={'verbose_name': 'Section 2', 'verbose_name_plural': 'Section 2'},
        ),
        migrations.AlterField(
            model_name='section2',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
