# Generated by Django 2.0.1 on 2018-02-05 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_auto_20180201_1134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section2',
        ),
    ]
